language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
notifications:
  irc:
    channels:
        - "chat.freenode.net#dokuwiki"
    on_success: change
    on_failure: change
install:
  - wget https://phar.phpunit.de/phpunit-4.3.5.phar -O _test/phpunit
  - chmod 755 _test/phpunit
script: cd _test && ./phpunit --verbose --stderr
