name: PHP Code Style

on: [push]

jobs:
    phpcs:
        name: PHP CodeSniffer
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Setup PHP
              uses: nanasess/setup-php@49cb618e1f511dc9ca5c3a56ad4aabdbf69a61fe
              with:
                  php-version: 7.3

            - name: Download PHPCS
              run: wget https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar

            - name: run PHP codesniffer
              run: php phpcs.phar -v --standard=_test/phpcs.xml
